---
apiVersion: projectcalico.org/v3
kind: NetworkSet
metadata:
  name: on-prem
  namespace: nginx-ingress
  labels:
    zone: on-prem
spec:
  nets:
  - 0.0.0.0/0

---
apiVersion: projectcalico.org/v3
kind: NetworkSet
metadata:
  name: kubernetes-api
  namespace: nginx-ingress
  labels:
    zone: kubernetes-api
spec:
  nets:
  - 192.168.56.101/32

---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  selector: app.kubernetes.io/name == 'ingress-nginx'
  types:
  - Egress
  - Ingress
  egress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from nginx to backend
    protocol: TCP
    destination:
      selector: app == 'webapp'
      namespaceSelector: projectcalico.org/name == 'webapp'
      ports:
      - 8080
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from nginx to k8s api
    protocol: TCP
    destination:
      selector: zone == 'kubernetes-api'
      ports:
      - 6443
  ingress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow ingress from on-onprem to nginx
    protocol: TCP
    source:
      selector: zone == 'on-prem'
    destination:
      ports:
      - 443

---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: dns
  namespace: nginx-ingress
spec:
  selector: all()
  types:
  - Egress
  egress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from all to kube-system for DNS
    protocol: UDP
    destination:
      selector: k8s-app == 'kube-dns'
      namespaceSelector: projectcalico.org/name == 'kube-system'
      ports:
      - 53
