---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  selector: app.kubernetes.io/name == 'ingress-nginx'
  types:
  - Egress
  - Ingress
  egress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from nginx to backend
    protocol: TCP
    destination:
      selector: app == 'webapp'
      namespaceSelector: projectcalico.org/name == 'webapp'
      ports:
      - 8080
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from nginx to k8s api
    protocol: TCP
    destination:
      selector: zone == 'kubernetes-api'
      ports:
      - 6443
  ingress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow ingress from on-onprem to nginx
    protocol: TCP
    source:
      selector: zone == 'on-prem'
    destination:
      ports:
      - 443
