---
apiVersion: projectcalico.org/v3
kind: NetworkSet
metadata:
  name: kubernetes-api
  namespace: nginx-ingress
  labels:
    zone: kubernetes-api
spec:
  nets:
  - 192.168.56.101/32

---
apiVersion: projectcalico.org/v3
kind: NetworkSet
metadata:
  name: on-prem
  namespace: nginx-ingress
  labels:
    zone: on-prem
spec:
  nets:
  - 192.168.56.0/24

---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  selector: app.kubernetes.io/name == 'ingress-nginx'
  types:
  - Egress
  - Ingress
  egress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from nginx to backend
    protocol: TCP
    destination:
      selector: app == 'webapp'
      namespaceSelector: projectcalico.org/name == 'webapp-demo'
      ports:
      - 8080
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from nginx to rogue
    protocol: TCP
    destination:
      selector: app == 'rogue'
      namespaceSelector: projectcalico.org/name == 'webapp-demo'
      ports:
      - 8080
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from nginx to hashi-demo presentation
    protocol: TCP
    destination:
      selector: app == 'presentation'
      namespaceSelector: projectcalico.org/name == 'hashi-demo'
      ports:
      - 80
  - action: Allow
    metadata:
      annotations:
        desc: Allow egress from nginx to k8s api
    protocol: TCP
    destination:
      selector: zone == 'kubernetes-api'
      ports:
      - 6443
  ingress:
  - action: Allow
    metadata:
      annotations:
        desc: Allow ingress from on-prem to nginx
    protocol: TCP
    source:
      selector: zone == 'on-prem'
    destination:
      ports:
      - 80
      - 443
