---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: mybanknamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: docker.io/steveszabo/webapp:289cf46
        imagePullPolicy: IfNotPresent
