---
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: mybank-namespace-label
  namespace: gatekeeper
spec:
  match:
    scope: Cluster
    kinds:
    - apiGroups: [""]
      kinds: ["Namespace"]
  location: "metadata.labels.cluster"
  parameters:
    assign:
      value:  "eng-cluster"
