---
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: mybankpod
  namespace: gatekeeper
spec:
  match:
    scope: Namespaced
    excludedNamespaces:
    - kube-system
    - kube-public
    - kube-node-lease
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  location: "spec.containers[name:*].imagePullPolicy"
  parameters:
    assign:
      value: Always
