---
apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: terminating-gateway
spec:
  services:
    - name: google
      caFile: /etc/ssl/cert.pem
    - name: elastic
      caFile: /etc/ssl/cert.pem
