---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: hashicups-frontend-to-consul
spec:
  destination:
    name: consul
  sources:
    - name: hashicups-frontend
      action: allow

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: hashicups-ingress-to-frontend
spec:
  destination:
    name: hashicups-frontend
  sources:
    - name: ingress-gateway
      action: allow

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: hashicups-frontend-to-google
spec:
  destination:
    name: external-google
  sources:
    - name: hashicups-frontend
      action: allow

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: hashicups-frontend-to-public
spec:
  destination:
    name: hashicups-public-api
  sources:
    - name: hashicups-frontend
      action: allow

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: hashicups-public-to-product
spec:
  destination:
    name: hashicups-product-api
  sources:
    - name: hashicups-public-api
      action: allow

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: hashicups-product-to-postgres
spec:
  destination:
    name: hashicups-postgres
  sources:
    - name: hashicups-product-api
      action: allow
