---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: hashicups-product-api
spec:
  routes:
    - match:
        http:
          pathPrefix: '/coffees'
      destination:
        service: 'hashicups-coffee-service'
