---
apiVersion: v1
kind: Service
metadata:
  name: hashicups-frontend
  labels:
    app: hashicups-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hashicups-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hashicups-frontend
automountServiceAccountToken: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  config: |
    # /etc/nginx/conf.d/default.conf
    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;
        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # Proxy pass the api location to save CORS
        # Use location exposed by Consul connect
        location /api {
            proxy_pass http://127.0.0.1:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashicups-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hashicups-frontend
      app: hashicups-frontend
  template:
    metadata:
      labels:
        service: hashicups-frontend
        app: hashicups-frontend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "hashicups-public-api:8080,external-google:9090,consul:8500"
        consul.hashicorp.com/enable-metrics-merging: "false"
    spec:
      serviceAccountName: hashicups-frontend
      volumes:
      - name: config
        configMap:
          name: nginx-configmap
          items:
          - key: config
            path: default.conf
      containers:
        - name: hashicups-frontend
          image: hashicorpdemoapp/frontend:v0.0.5
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
              readOnly: true
