---
apiVersion: v1
kind: Service
metadata:
  name: hashicups-postgres
  labels:
    app: hashicups-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: hashicups-postgres
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hashicups-postgres
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashicups-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hashicups-postgres
      app: hashicups-postgres
  template:
    metadata:
      labels:
        service: hashicups-postgres
        app: hashicups-postgres
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/enable-metrics-merging: "false"
    spec:
      serviceAccountName: hashicups-postgres
      containers:
        - name: hashicups-postgres
          image: hashicorpdemoapp/product-api-db:v0.0.16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: products
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          # only listen on loopback so only access is via connect proxy
          args: ["-c", "listen_addresses=127.0.0.1"]
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "pgdata"
      volumes:
        - name: pgdata
          emptyDir: {}
