---
apiVersion: v1
kind: Service
metadata:
  name: hashicups-product-api
spec:
  selector:
    app: hashicups-product-api
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hashicups-product-api
automountServiceAccountToken: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  config: |
    {
      "db_connection": "host=localhost port=5432 user=postgres password=password dbname=products sslmode=disable",
      "bind_address": ":9090",
      "metrics_address": ":9103"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashicups-product-api
  labels:
    app: hashicups-product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashicups-product-api
  template:
    metadata:
      labels:
        app: hashicups-product-api
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "hashicups-postgres:5432"
        consul.hashicorp.com/enable-metrics-merging: "false"
    spec:
      serviceAccountName: hashicups-product-api
      volumes:
      - name: config
        configMap:
          name: db-configmap
          items:
          - key: config
            path: conf.json
      containers:
        - name: hashicups-product-api
          image: hashicorpdemoapp/product-api:v0.0.16
          ports:
            - containerPort: 9090
            - containerPort: 9103
          env:
            - name: "CONFIG_FILE"
              value: "/config/conf.json"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 30
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
