---
apiVersion: v1
kind: Service
metadata:
  name: hashicups-public-api
  labels:
    app: hashicups-public-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hashicups-public-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hashicups-public-api
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashicups-public-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hashicups-public-api
      app: hashicups-public-api
  template:
    metadata:
      labels:
        service: hashicups-public-api
        app: hashicups-public-api
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "hashicups-product-api:9090"
        consul.hashicorp.com/enable-metrics-merging: "false"
    spec:
      serviceAccountName: hashicups-public-api
      containers:
        - name: hashicups-public-api
          image: hashicorpdemoapp/public-api:v0.0.5
          ports:
            - containerPort: 8080
          env:
            - name: BIND_ADDRESS
              value: ":8080"
            - name: PRODUCT_API_URI
              value: "http://localhost:9090"
