---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: flux-applications
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: flux-applications
  policy:
    semver:
      range: x.x.x
