---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-demo
  template:
    metadata:
      labels:
        app: webapp-demo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - webapp-demo
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: webapp-demo
      containers:
      - name: webapp
        image: docker.io/steveszabo/webapp:e45ad1f
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128M
          limits:
            cpu: 200m
            memory: 256M
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /
            port: http
        readinessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /
            port: http
