#!/bin/bash

set -o errexit

DOCKER_VERSION=$(echo $GITHUB_SHA | cut -c1-7)
DOCKER_FILE=Dockerfile

DOCKER_IMAGE=$DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_REPOSITORY:$DOCKER_VERSION

sed -i "s/WEBAPP_VERSION=.*/WEBAPP_VERSION=$DOCKER_VERSION/g" $DOCKER_FILE

docker build -t $DOCKER_IMAGE -f $DOCKER_FILE .
docker push $DOCKER_IMAGE

exit 0
