#!/bin/bash

set -o errexit

DOCKER_VERSION=$(date +%s)
DOCKER_VERSION=$GITHUB_JOB
DOCKER_FILE=Dockerfile

DOCKER_IMAGE=$DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_REPOSITORY:$DOCKER_VERSION

sed -i "s/WEBAPP_VERSION=.*/WEBAPP_VERSION=$DOCKER_VERSION/g" $DOCKER_FILE

echo docker build -t $DOCKER_IMAGE -f $DOCKER_FILE .
echo docker push $DOCKER_IMAGE

exit 0
