FROM ubuntu:latest
MAINTAINER steve.g.szabo

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl wget python3 python3-pip gunicorn && \
    apt-get clean && \
    pip3 install flask
