---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubecost
  namespace: tools-kubecost
spec:
  ingressClassName: nginx
  rules:
  - host: ingress-kubecost.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: r1-cost-analyzer
            port:
              number: 9090
