---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hashi-data-vault-0
  labels:
    app: hashi-vault
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-nfs-storage
  nfs:
    path: /srv/shared/hashi-data-vault-0
    server: 192.168.56.201

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hashi-audit-vault-0
  labels:
    app: hashi-vault
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-nfs-storage
  nfs:
    path: /srv/shared/hashi-audit-vault-0
    server: 192.168.56.201
