---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: boot
  namespace: tools-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: ArgoCD bootstrap project
  sourceRepos:
  - https://github.com/stevegszabo/argocd-example-apps.git
  destinations:
  - server: https://192.168.56.201:6443
    namespace: tools-argocd

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: webapp-demo
  namespace: tools-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: ArgoCD webapp-demo project
  sourceRepos:
  - https://github.com/stevegszabo/argocd-example-apps.git
  destinations:
  - server: https://192.168.56.201:6443
    namespace: webapp-demo
