---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-demo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: argo-demo=docker.io/steveszabo/webapp
    argocd-image-updater.argoproj.io/argo-demo.update-strategy: latest
    argocd-image-updater.argoproj.io/argo-demo.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/argo-demo.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/repo-private-ssh
    argocd-image-updater.argoproj.io/git-branch: master
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: argo-demo
  source:
    repoURL: git@github.com:stevegszabo/argocd-example-apps.git
    targetRevision: HEAD
    path: webapp
    helm:
      releaseName: argo-demo
      values: |
        image:
          repository: docker.io/steveszabo/webapp
          tag: ea5400a
        annotations:
          kubernetes.io/change-cause: "argo-demo-001"
        scaling:
          minReplicas: 4
        ingress:
          enabled: false
        hpa:
          enabled: false
        resources:
          requests:
            cpu: 100m
            memory: 64M
          limits:
            cpu: 200m
            memory: 128M
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
