---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  project: argo-demo
  source:
    repoURL: git@github.com:stevegszabo/argocd-example-apps.git
    targetRevision: HEAD
    path: webapp
    helm:
      releaseName: webapp
      parameters:
      - name: image.repository
        value: "notebook.local:5000/webapp"
      - name: image.tag
        value: "6.0.1"
      - name: ingress.enabled
        value: "false"
      - name: hpa.enabled
        value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
