---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashi-demo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: hashi-demo
  source:
    repoURL: git@github.com:stevegszabo/argocd-example-apps.git
    targetRevision: HEAD
    path: hashi-demo
  destination:
    server: https://10.0.2.15:6443
    namespace: hashi-demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
