---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: webapp=notebook.local:5000/webapp
    argocd-image-updater.argoproj.io/webapp.update-strategy: latest
    argocd-image-updater.argoproj.io/webapp.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/webapp.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: argo-demo
  source:
    repoURL: git@github.com:stevegszabo/argocd-example-apps.git
    targetRevision: HEAD
    path: webapp
    helm:
      releaseName: webapp
      parameters:
      - name: image.repository
        value: "notebook.local:5000/webapp"
      - name: image.tag
        value: "6.0.1"
      - name: scaling.minReplicas
        value: "1"
      - name: ingress.enabled
        value: "false"
      - name: hpa.enabled
        value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
