---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recluse
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: recluse=notebook.local:5000/webapp
    argocd-image-updater.argoproj.io/recluse.update-strategy: latest
    argocd-image-updater.argoproj.io/recluse.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/recluse.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/repo-private-ssh
    argocd-image-updater.argoproj.io/git-branch: master
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: argo-demo
  source:
    repoURL: git@github.com:stevegszabo/argocd-example-apps.git
    targetRevision: HEAD
    path: webapp
    helm:
      releaseName: recluse
      values: |
        image:
          repository: notebook.local:5000/webapp
          tag: 6.2.3
        annotations:
          kubernetes.io/change-cause: "recluse-003"
        scaling:
          minReplicas: 4
        ingress:
          enabled: false
        hpa:
          enabled: false
        resources:
          requests:
            cpu: 103m
            memory: 64M
          limits:
            cpu: 200m
            memory: 128M
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
