---
apiVersion: v1
kind: Secret
metadata:
  name: repo-docker-token
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
stringData:
  .dockerconfigjson: |
    {"auths": {"https://index.docker.io/v1/": {"auth": "XXXXXXXXXXXXX"}}}
