FROM 192.168.56.101:5000/ubuntu-flask:latest
MAINTAINER steve.g.szabo@gmail.com

ENV WEBAPP_VERSION=1.0.16

COPY root/app /app
RUN chown -R www-data:www-data /app
EXPOSE 8080
USER www-data
ENTRYPOINT ["/app/entrypoint.sh"]
