---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: webapp-csi
spec:
  provider: vault
  parameters:
    vaultAddress: http://r1-vault.tools-hashi-vault:8200
    vaultKubernetesMountPath: eng-cluster
    roleName: webapp
    objects: |
      - objectName: POSTGRES_USER
        secretPath: webapp-demo/data/webapp/config
        secretKey: username
      - objectName: POSTGRES_PASSWORD
        secretPath: webapp-demo/data/webapp/config
        secretKey: password
  secretObjects:
  - data:
    - key: POSTGRES_USER
      objectName: POSTGRES_USER
    - key: POSTGRES_PASSWORD
      objectName: POSTGRES_PASSWORD
    secretName: webapp-csi
    type: Opaque

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-csi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-csi
  annotations:
    secret.reloader.stakater.com/reload: "webapp-csi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-csi
  template:
    metadata:
      labels:
        app: webapp-csi
    spec:
      volumes:
      - name: webapp-csi
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: webapp-csi
      serviceAccountName: webapp-csi
      containers:
      - name: webapp
        image: docker.io/steveszabo/webapp:289cf46
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: webapp-csi
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webapp-csi
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: webapp-csi
          mountPath: /csi/secrets
          readOnly: true
