---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-demo
  annotations:
    secret.reloader.stakater.com/reload: "webapp-demo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-demo
  template:
    metadata:
      labels:
        app: webapp-demo
    spec:
      volumes:
      - name: webapp-demo
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: webapp-demo
      serviceAccountName: webapp
      containers:
      - name: webapp
        image: docker.io/steveszabo/webapp:289cf46
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: webapp-demo
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webapp-demo
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: webapp-demo
          mountPath: /csi/secrets
          readOnly: true
