---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-csi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-csi
  annotations:
    secret.reloader.stakater.com/reload: "webapp-csi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-csi
  template:
    metadata:
      labels:
        app: webapp-csi
    spec:
      volumes:
      - name: webapp-csi
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: webapp-csi
      serviceAccountName: webapp-csi
      containers:
      - name: webapp
        image: docker.io/steveszabo/webapp:289cf46
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: webapp-csi
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webapp-csi
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: webapp-csi
          mountPath: /csi/secrets
          readOnly: true
