---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  progressDeadlineSeconds: 120
  minReadySeconds: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: client
        version: v1
      annotations:
        kubernetes.io/change-cause: "001"
    spec:
      containers:
      - name: curl-webapp
        image: notebook.local:5000/webapp:latest
        command: ["/bin/bash", "-c", "while true; do curl -s http://webapp.demo.svc.cluster.local/webapp; sleep .5; done"]
      - name: curl-google
        image: notebook.local:5000/webapp:latest
        command: ["/bin/bash", "-c", "while true; do curl -s https://www.google.com; sleep .5; done"]
      - name: client
        image: notebook.local:5000/webapp:latest
        ports:
        - name: client
          containerPort: 8080
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: client
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: client
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
