---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presentation
  labels:
    app: presentation
    version: v1
spec:
  selector:
    matchLabels:
      app: presentation
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: presentation
        version: v1
      annotations:
        kubernetes.io/change-cause: "001"
    spec:
      containers:
      - name: curl-backend
        image: notebook.local:5000/webapp:latest
        command: ["/bin/bash", "-c", "while true; do curl -v http://$HASHI_BACK/api/posts; sleep 1; done"]
        env:
        - name: HASHI_BACK
          value: "application.hashi-demo.svc.cluster.local:5000"
      - name: presentation
        image: notebook.local:5000/hashi-demo/hashi-demo-web:dfd2e2b-dirty
        env:
        - name: APPLICATION_BACK
          value: "application.hashi-demo.svc.cluster.local:5000"
        ports:
        - containerPort: 80
          name: presentation
        resources:
          requests:
            cpu: 256m
            memory: 256M
          limits:
            cpu: 256m
            memory: 256M
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 15
          httpGet:
            path: /probe.html
            port: presentation
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 15
          httpGet:
            path: /probe.html
            port: presentation

---
apiVersion: v1
kind: Service
metadata:
  name: presentation
  labels:
    app: presentation
spec:
  selector:
    app: presentation
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: presentation
  labels:
    app: presentation
spec:
  host: presentation.hashi-demo.svc.cluster.local
  subsets:
  - name: v1
    labels:
      app: presentation
      version: v1

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: presentation
  labels:
    app: presentation
spec:
  hosts:
  - presentation.hashi-demo.svc.cluster.local
  - hashi-demo.example.com
  gateways:
  - hashi-demo
  - mesh
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: presentation.hashi-demo.svc.cluster.local
        subset: v1
        port:
          number: 80
