---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
  labels:
    app: hashi-demo
    tier: data
    version: v1
spec:
  selector:
    matchLabels:
      tier: data
  replicas: 1
  template:
    metadata:
      name: data
      labels:
        app: hashi-demo
        tier: data
        version: v1
      annotations:
        kubernetes.io/change-cause: "001"
    spec:
      volumes:
      - name: hashi-demo
        persistentVolumeClaim:
          claimName: hashi-demo
      containers:
      - name: data
        image: 192.168.56.101:5000/hashi-demo/hashi-demo-data:latest
        volumeMounts:
        - name: hashi-demo
          mountPath: /database
        env:
        - name: PGDATA
          value: "/database/data"
        ports:
        - name: data
          containerPort: 5432
        resources:
          requests:
            cpu: 256m
            memory: 256M
          limits:
            cpu: 256m
            memory: 256M
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 15
          exec:
            command: ["psql", "-w", "-U", "postgres", "-d", "posts", "-c", "SELECT 1"]
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 15
          exec:
            command: ["psql", "-w", "-U", "postgres", "-d", "posts", "-c", "SELECT 1"]

---
apiVersion: v1
kind: Service
metadata:
  name: data
  labels:
    app: hashi-demo
    tier: data
spec:
  type: ClusterIP
  selector:
    app: hashi-demo
    tier: data
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
    protocol: TCP

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: data
  labels:
    app: hashi-demo
    tier: data
spec:
  host: data.hashi-demo.svc.cluster.local
  subsets:
  - name: v1
    labels:
      app: hashi-demo
      tier: data
      version: v1
