---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: application
    version: v1
spec:
  selector:
    matchLabels:
      app: application
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: application
        version: v1
      annotations:
        kubernetes.io/change-cause: "001"
    spec:
      containers:
      - name: application
        image: notebook.local:5000/hashi-demo/hashi-demo-app:dfd2e2b-dirty
        env:
        - name: POSTGRES_HOST
          value: "data.hashi-demo.svc.cluster.local"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres_password"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DATABASE
          value: "posts"
        ports:
        - name: application
          containerPort: 5000
        resources:
          requests:
            cpu: 256m
            memory: 256M
          limits:
            cpu: 256m
            memory: 256M
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 15
          httpGet:
            path: /api/probe
            port: application
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 15
          httpGet:
            path: /api/probe
            port: application

---
apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: application
spec:
  selector:
    app: application
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: application
  labels:
    app: application
spec:
  host: application.hashi-demo.svc.cluster.local
  subsets:
  - name: v1
    labels:
      app: application
      version: v1

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: application
  labels:
    app: application
spec:
  hosts:
  - application.hashi-demo.svc.cluster.local
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: application.hashi-demo.svc.cluster.local
        subset: v1
        port:
          number: 5000
