apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: hashi-demo
build:
  artifacts:
  - image: 192.168.56.101:5000/hashi-demo/hashi-demo-app
    context: app-tier
    docker:
      dockerfile: Dockerfile
  - image: 192.168.56.101:5000/hashi-demo/hashi-demo-data
    context: db-tier
    docker:
      dockerfile: Dockerfile
  - image: 192.168.56.101:5000/hashi-demo/hashi-demo-web
    context: frontend-tier
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deploy.hashi-app.yaml
    - deploy.hashi-data.yaml
    - deploy.hashi-web.yaml
