---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-config: "webapp-demo/webapp/config"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "webapp-demo/webapp/config" -}}
          MYSQL_USERNAME={{ .Data.data.username }}
          MYSQL_PASSWORD={{ .Data.data.password }}
          export MYSQL_USERNAME MYSQL_PASSWORD
          {{- end }}
        vault.hashicorp.com/auth-path: "auth/eng-cluster"
        vault.hashicorp.com/role: "webapp"
        vault.hashicorp.com/tls-skip-verify: "true"
    spec:
      serviceAccountName: webapp
      containers:
      - name: webapp
        image: docker.io/steveszabo/webapp:5744671
