apiVersion: ENC[AES256_GCM,data:hQQ=,iv:8UkBcHLfMdNZ/v7QCXvRYAELrNZfxKMkkFz2tsamsys=,tag:zUx6wXK4aQ4xmmwmnm11UA==,type:str]
kind: ENC[AES256_GCM,data:X75XhIpmyfuX10UOGRA=,iv:sO/dMvy/9foGYA9mL6WfnKfRldEsHtNLUAAABM39vGk=,tag:1MlqVNWgn9ppfYC284T12w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vfWRAcVU/dMKlJTXQq023CgW,iv:kokRm/xFufKrslbEEEmez1uqlwForDbp3CpY6xa4qII=,tag:9Ss6EMn1VPRfS6m63JnrHQ==,type:str]
    namespace: ENC[AES256_GCM,data:GGh25Ml+Fw==,iv:rMNY+xQ4AFzTGwQM4G+ikVzcPzo8pxmI+94Xe93IUJQ=,tag:PyoQr4EHNJRfLQtnmjxLoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18affr3vq66ehdmp49qhlpv9lclw2rjl4w4qdxwasz8szdvyqwczsqfjkca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVG16ME1CZzNNWDF1eStE
            VG5FaHNMc1FBdjFsNWcycEc2ZW5wZjNLY0VjCmVkOXpUZ0JJRzE1WXFuZ2VpU2Nx
            SVRwRzVwVUhEQUVSMFF6a1BhZDhEalEKLS0tIGlvejZEY01XRWdkKzZuMGhNdlhN
            UFBreGJmMjREaWJBV2lDdUJwR1EvemsKtqc2aDR/LaFuadhCc4NjmXYtZP183IXt
            2m83WRbIHdOBndn8csQbEnusp7IVnzmK7f9d8GWz81MkOxBL9duPig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-13T23:41:58Z"
    mac: ENC[AES256_GCM,data:FAkUaVhm+dcPFvniSqeetRc7ucE9d/TnLDe+R9bxfN41MxcSbWCtYBjFHtp4OZano8AoVum324rxY/4GEkyDi5CnAI4C4T+9i5+RGfzCxFmZwNX4sx08VOQwoOI3MIoxF/m6YYpa6AQ5BHchcmZ3UDOj81r1J3lEn9FzCJbNTbM=,iv:LouPl1ztyqh/v451TkdnWbrYtI7eEl2W8Fr2SLXzQfQ=,tag:ipof89aCciCTKyXltsHbcA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
---
apiVersion: ENC[AES256_GCM,data:JbQ=,iv:Q2u3zOl7nQ9JAdLY4Zy6qeD/9Nv2uevpiRqTWhbdHSA=,tag:s56Uc3SrYRBGTEWfHpcrRg==,type:str]
kind: ENC[AES256_GCM,data:pi1NBFp5cWOsgA27qiU=,iv:wvpq1KjDmtMJYKLuPJ5yCv1oTJLnHWz24W/rvwX1IMA=,tag:tHmcKCRkEfRv8SRBvAudkw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kU2XGZAW6MNPnQ==,iv:J0Zrp/I8xr/Z140AKfYzdNnyMCxNWbOlgdim7r97G7Y=,tag:+SNFLZYRD+Mj7NjsVpQVpw==,type:str]
    namespace: ENC[AES256_GCM,data:Uik/uRuQotYR,iv:jAEtpHL4W9ujbHSdJ6BqpwbzNTfxxwPN300GTzsnvm4=,tag:8b2pZLmhv/jxF7kbw67hrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18affr3vq66ehdmp49qhlpv9lclw2rjl4w4qdxwasz8szdvyqwczsqfjkca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVG16ME1CZzNNWDF1eStE
            VG5FaHNMc1FBdjFsNWcycEc2ZW5wZjNLY0VjCmVkOXpUZ0JJRzE1WXFuZ2VpU2Nx
            SVRwRzVwVUhEQUVSMFF6a1BhZDhEalEKLS0tIGlvejZEY01XRWdkKzZuMGhNdlhN
            UFBreGJmMjREaWJBV2lDdUJwR1EvemsKtqc2aDR/LaFuadhCc4NjmXYtZP183IXt
            2m83WRbIHdOBndn8csQbEnusp7IVnzmK7f9d8GWz81MkOxBL9duPig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-13T23:41:58Z"
    mac: ENC[AES256_GCM,data:FAkUaVhm+dcPFvniSqeetRc7ucE9d/TnLDe+R9bxfN41MxcSbWCtYBjFHtp4OZano8AoVum324rxY/4GEkyDi5CnAI4C4T+9i5+RGfzCxFmZwNX4sx08VOQwoOI3MIoxF/m6YYpa6AQ5BHchcmZ3UDOj81r1J3lEn9FzCJbNTbM=,iv:LouPl1ztyqh/v451TkdnWbrYtI7eEl2W8Fr2SLXzQfQ=,tag:ipof89aCciCTKyXltsHbcA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
---
apiVersion: ENC[AES256_GCM,data:4q2WQI71rAT1uPBaqPK0f7f4rwnqp8f4q1LCyw==,iv:67LeBMM2Y0SH1DH2zjFfMWc3TNCvvQpd9umuRgKl5jQ=,tag:OfPDeI4XG/TgeGJINhm+fw==,type:str]
kind: ENC[AES256_GCM,data:2FHsc/q+hJZj1qzsbP32Qg+3,iv:ugjy4z1kK+eU64bfKvNWCY6iC+H9h+JojFNE/dwywcE=,tag:+A3WGQ8pUaxQqnUUxSj3rA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QCw1GBx87tmeiwNqmxRa47iz,iv:tKZcSHBpWFBvVrKIXuhBBFri8Pc7tO1e6MclojpgK7o=,tag:ke0r/cdV0G266LjQBFnGpg==,type:str]
roleRef:
    apiGroup: ENC[AES256_GCM,data:Di34g/5Gr1aLRdZV3UynUEDjgh4pI3q9gA==,iv:x/I/LIjKrEmlCtj6V32zBrNUmgSuV/xe9X35bo56O94=,tag:q5TVdATN1zZOidXgfozLLw==,type:str]
    kind: ENC[AES256_GCM,data:NGSZM4/TqK18AXs=,iv:By2GaqZWg/SGOOJLL1hTmnbT/z3IEZBcm0MU9lS3CJs=,tag:QhCzjHOfq02fu2k9SRZgyQ==,type:str]
    name: ENC[AES256_GCM,data:fKoZ2stloRHsYpeD9qLGB76/t2tr,iv:Z5tLF3/XX+UhKDkyVJJnuK30KAYSq73VXj+L4+PJ1oY=,tag:mVXLUIHCzvp3J3eq4xeUoQ==,type:str]
subjects:
    - kind: ENC[AES256_GCM,data:akrtUVRSpQp7WANRz3Y=,iv:ZQ3jY4iUk5y6OP2SshPbTiwiHWOFWpoDTm036Lztz+0=,tag:1jWRfdTP+JvlANd/PuN5Ig==,type:str]
      name: ENC[AES256_GCM,data:zuPmc1i3ynIFPWuRztp77pLW,iv:t/PKmAPW8VRxkaFgoeMmBPQ9XO//w3C2KEUQIdvHCuQ=,tag:W/RM0b8U7wxSorWxPSivxg==,type:str]
      namespace: ENC[AES256_GCM,data:/iCfh8wVfw==,iv:hMKM5VkzvgJo7rZHZhsr+lwmdHfm5SDVG+jICbofLzY=,tag:w4QZpNNWg7r3ukmsrxqUgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18affr3vq66ehdmp49qhlpv9lclw2rjl4w4qdxwasz8szdvyqwczsqfjkca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVG16ME1CZzNNWDF1eStE
            VG5FaHNMc1FBdjFsNWcycEc2ZW5wZjNLY0VjCmVkOXpUZ0JJRzE1WXFuZ2VpU2Nx
            SVRwRzVwVUhEQUVSMFF6a1BhZDhEalEKLS0tIGlvejZEY01XRWdkKzZuMGhNdlhN
            UFBreGJmMjREaWJBV2lDdUJwR1EvemsKtqc2aDR/LaFuadhCc4NjmXYtZP183IXt
            2m83WRbIHdOBndn8csQbEnusp7IVnzmK7f9d8GWz81MkOxBL9duPig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-13T23:41:58Z"
    mac: ENC[AES256_GCM,data:FAkUaVhm+dcPFvniSqeetRc7ucE9d/TnLDe+R9bxfN41MxcSbWCtYBjFHtp4OZano8AoVum324rxY/4GEkyDi5CnAI4C4T+9i5+RGfzCxFmZwNX4sx08VOQwoOI3MIoxF/m6YYpa6AQ5BHchcmZ3UDOj81r1J3lEn9FzCJbNTbM=,iv:LouPl1ztyqh/v451TkdnWbrYtI7eEl2W8Fr2SLXzQfQ=,tag:ipof89aCciCTKyXltsHbcA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
