---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: presentation

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: application

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data
