---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-v2
  labels:
    app: application
    version: v2
spec:
  selector:
    matchLabels:
      app: application
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: application
        version: v2
      annotations:
        kubernetes.io/change-cause: "001"
    spec:
      serviceAccountName: application
      containers:
      - name: application
        image: notebook.local:5000/hashi-demo/hashi-demo-app:2.0.0
        env:
        - name: POSTGRES_HOST
          value: "data.hashi-demo.svc.cluster.local"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres_password"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DATABASE
          value: "posts"
        ports:
        - name: application
          containerPort: 5000
        resources:
          requests:
            cpu: 256m
            memory: 256M
          limits:
            cpu: 256m
            memory: 256M
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 15
          httpGet:
            path: /api/probe
            port: application
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 15
          httpGet:
            path: /api/probe
            port: application
