---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hashi-demo
  labels:
    app: data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: managed-nfs-storage
  nfs:
    path: /srv/shared/hashi-demo
    server: notebook.local

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hashi-demo
  labels:
    app: data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
