---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: MybankNamespace
metadata:
  name: mybanknamespace
  namespace: gatekeeper
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Namespace"]
  parameters:
    labels: ["environment", "application"]
