---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webapp-demo
  namespace: app-webapp-demo
spec:
  ca:
    secretName: webapp-demo-ca

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webapp-demo
  namespace: app-webapp-demo
spec:
  commonName: www.webapp.com
  secretName: webapp-demo
  dnsNames:
  - www.webapp.ca
  - www.webapp.net
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: webapp-demo
    kind: Issuer
    group: cert-manager.io
