---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: eng-cluster
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webapp-demo-ca
  namespace: app-webapp-demo
spec:
  isCA: true
  commonName: webapp-demo-ca
  secretName: webapp-demo-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: eng-cluster
    kind: ClusterIssuer
    group: cert-manager.io