name: docker-build
on: [push]
jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: uname -a
  image-push:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
